from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from openfep.constants import (
    COMPLEX_BUFFER_WIDTH,
    NET_CHARGE_COMPLEX_BUFFER_WIDTH,
    StrucTag,
)
from openfep.mae_parser import parse_mae
from openfep.mapping.base import AtomMapping


@dataclass
class RBFESystem:
    fmp_path: Path
    atom_mapping_paths: dict[str, Path] = field(default_factory=dict)
    receptor_count: int = 1
    is_charged: bool = False
    buffer_width: float = COMPLEX_BUFFER_WIDTH
    has_membrane: bool = False


def prepare_rbfe(
    mae_path: Path,
    output_dir: Path,
    mappings: list[tuple[str, str, AtomMapping]],
    jobname: str = "rbfe",
) -> RBFESystem:
    """
    Prepare RBFE input files.
    mappings: list of (lig_a_name, lig_b_name, AtomMapping)
    Writes: {jobname}.fmp and {edge_key}_atom_mapping.txt files in output_dir.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    ct_blocks = parse_mae(mae_path)

    # Detect net charge from any ligand CT
    is_charged = _detect_net_charge(ct_blocks)
    has_membrane = any(ct.struc_tag == StrucTag.MEMBRANE for ct in ct_blocks)
    receptor_count = _compute_receptor_count(ct_blocks)
    buffer_width = (
        NET_CHARGE_COMPLEX_BUFFER_WIDTH if is_charged else COMPLEX_BUFFER_WIDTH
    )

    # Write atom mapping files
    mapping_paths: dict[str, Path] = {}
    for lig_a, lig_b, mapping in mappings:
        edge_key = f"{lig_a}_to_{lig_b}"
        p = output_dir / f"{edge_key}_atom_mapping.txt"
        _write_atom_mapping(p, mapping)
        mapping_paths[edge_key] = p

    # Write .fmp file
    fmp_path = output_dir / f"{jobname}.fmp"
    _write_fmp(fmp_path, mappings, mae_path)

    return RBFESystem(
        fmp_path=fmp_path,
        atom_mapping_paths=mapping_paths,
        receptor_count=receptor_count,
        is_charged=is_charged,
        buffer_width=buffer_width,
        has_membrane=has_membrane,
    )


def _detect_net_charge(ct_blocks) -> bool:
    """Return True if any ligand CT has non-zero i_fep_net_charge."""
    for ct in ct_blocks:
        if ct.struc_tag != StrucTag.LIGAND:
            continue
        # Find i_fep_net_charge in header and read its value using a
        # state-machine that mirrors _extract_struc_tag in mae_parser.py
        lines = ct.raw_block.splitlines()
        prop_names: list[str] = []
        values: list[str] = []
        sep_count = 0
        state = "header"
        for line in lines[1:]:   # skip "f_m_ct {"
            stripped = line.strip()
            if stripped == ":::":
                sep_count += 1
                state = "values" if sep_count == 1 else "done"
                if state == "done":
                    break
                continue
            if state == "header":
                if stripped and not stripped.startswith("#"):
                    prop_names.append(stripped)
            elif state == "values":
                if stripped:
                    values.append(stripped)
        if "i_fep_net_charge" in prop_names:
            idx = prop_names.index("i_fep_net_charge")
            if idx < len(values):
                try:
                    if int(values[idx]) != 0:
                        return True
                except ValueError:
                    pass
    return False


def _compute_receptor_count(ct_blocks) -> int:
    count = 1  # always: the protein
    if any(ct.struc_tag == StrucTag.SOLVENT for ct in ct_blocks):
        count += 1
    if any(ct.struc_tag == StrucTag.MEMBRANE for ct in ct_blocks):
        count += 1
    return count


def _write_atom_mapping(path: Path, mapping: AtomMapping) -> None:
    lines = ["# atom_a_idx\tatom_b_idx\n"]
    for ia, ib in sorted(mapping.a_to_b.items()):
        lines.append(f"{ia}\t{ib}\n")
    path.write_text("".join(lines), encoding="utf-8")


def _write_fmp(
    path: Path,
    mappings: list[tuple[str, str, AtomMapping]],
    mae_path: Path,
) -> None:
    """
    Write the FEP Map (.fmp) file.

    NOTE: The reference fep_mapper.py uses Graph.deserialize / g.write in
    schrodinger.application.scisol.fep.graph — a proprietary binary/SEA format
    that requires the Schrodinger Python stack,
    which is prohibited in openfep. This function writes a plain-text edge-list
    placeholder that documents the graph topology. The actual .fmp file consumed
    at runtime is generated by the Desmond fep_mapper.py subprocess when
    graph_file is not specified in the MSJ fep_mapper stage.
    """
    lines = ["# FEP Map — generated by openfep\n"]
    lines.append(f"structure_file = {mae_path}\n")
    for lig_a, lig_b, _ in mappings:
        lines.append(f"edge {lig_a} {lig_b}\n")
    path.write_text("".join(lines), encoding="utf-8")
